const text = [
  `The early morning mist clung to the fields like a veil, softening the landscape into an ethereal dream. The sun had barely begun to rise, casting faint rays that barely touched the ground but painted the sky in shades of lavender and gold. Birds, still half-asleep, chirped lazily from the trees, their voices barely a whisper against the silence of the dawn. The air was crisp, carrying the scent of dew-covered grass and fresh earth. Each breath was a reminder of the stillness that comes before the world awakens in full. The only sound, aside from the birds, was the occasional rustling of leaves as the wind made its slow approach. It was a moment suspended in time, an invitation to pause and take in the quiet beauty before the rush of the day began. Everything felt fresh and new, as though the world had just been born again with the light of the morning.`,
  `The streets of the old town wound through narrow alleys and cobbled lanes, each corner revealing a piece of history. The buildings, though weathered by time, stood proudly, their facades telling stories of centuries gone by. Hanging flower baskets adorned windowsills, bursting with color against the muted tones of the stone walls. The scent of freshly baked bread drifted from a bakery, mingling with the earthy smell of rain on old brick. A small fountain in the square gurgled softly, its water catching the light as it splashed into the stone basin below. In the distance, the bell tower of the church rang the hour, its deep chimes echoing off the walls. People moved through the streets at a leisurely pace, exchanging friendly nods and greetings. There was a warmth to the town, a sense of community that seemed timeless, as if the pace of life had always been this gentle.`,
  `The mountains rose before me, their snow-capped peaks sharp against the clear blue sky. The air up here was thin, crisp with the scent of pine and cold stone. As I made my way up the trail, the ground beneath my boots crunched with each step, the silence of the forest broken only by the occasional rustling of leaves in the wind. The landscape shifted as I ascended—dense forests of fir trees giving way to barren rocky outcrops, and then, further still, to fields of alpine flowers and grass that swayed gently in the breeze. The view from the top was unlike anything I had ever seen—a vast expanse of valleys and ridgelines stretching for miles, untouched and wild. It was humbling to stand at the peak, surrounded by the rugged beauty of nature, and to feel the quiet power of the earth beneath me.`,
  `The city at night was a different creature altogether. The streets, once crowded and busy, were now quiet, save for the hum of distant traffic and the occasional car passing by. Streetlights cast long shadows, illuminating the pavement with pools of golden light. In the distance, the skyline of the city was dotted with the glowing windows of high-rise buildings, their lights twinkling like stars against the darkened sky. There was a certain magic to the night, a sense of mystery that seemed to permeate the air. People moved through the streets in solitude, each person wrapped in their own thoughts, yet all connected by the shared experience of the city's quiet rhythm. The night was a time for reflection, for moments of stillness in the middle of an otherwise bustling world.`,
  `The ocean stretched out before me, a vast expanse of blue that seemed to go on forever. The waves rolled in rhythmically, their white-tipped crests crashing against the shore with a thunderous roar. Seagulls circled overhead, their cries echoing in the salt-laden air. The sand beneath my feet was warm, the grains fine and soft, slipping through my toes like liquid. The sun beat down, warming my skin, while the breeze coming off the water carried a coolness that was both refreshing and invigorating. As I walked along the shoreline, the sound of the surf was a constant companion, soothing in its repetition. The scent of salt and seaweed filled my nostrils, grounding me in the moment. The ocean was wild and untamed, its power undeniable, yet there was a peace in the way it embraced the shore, a harmony in the rhythm of its waves.`,
  `The forest was alive with the sounds of life, each creature contributing its own note to the symphony of nature. The wind whispered through the branches, causing the leaves to tremble in response. Birds flitted from tree to tree, their songs echoing through the canopy. Beneath the trees, the ground was soft with moss, and the air was thick with the earthy scent of soil and decaying leaves. Sunlight filtered through the canopy, creating patches of warmth that seemed to dance on the forest floor. The deeper I walked, the more the forest seemed to close in around me, its ancient trees towering above, their gnarled roots winding through the earth like veins. There was something primal about the forest, as though it held the secrets of the world in its depths, waiting to be discovered by those patient enough to listen.`,
  `The small café tucked away on a quiet street corner was a haven from the world outside. Inside, the scent of freshly ground coffee filled the air, mingling with the warmth of the wooden floors and the soft murmur of conversation. People sat at tables, some alone with their books or laptops, others in pairs, deep in quiet conversation. The barista behind the counter worked with practiced ease, crafting each drink with care, the steam rising from the espresso machine adding to the cozy atmosphere. The soft jazz music playing in the background created a relaxed ambiance, perfect for moments of solitude or intimate discussion. Outside, the world moved on, but in here, time seemed to slow. It was a place of quiet refuge, where the hustle of life could be put on pause, even if just for a moment.`,
  `The stars twinkled above, a million tiny lights scattered across the night sky like glitter. The air was cool and crisp, the kind of night where every breath seemed to carry the freshness of the outdoors. The world below was quiet, the sounds of the day now silenced by the blanket of night. The only noise was the soft rustle of leaves in the wind and the occasional chirp of a distant cricket. As I gazed up at the sky, it felt as though I could reach out and touch the stars, as though they were within arm's reach, just beyond the veil of atmosphere. There was something humbling about the vastness of the universe, the way the stars seemed to stretch on forever, a reminder of how small we are in the grand scheme of things. And yet, in that moment, it felt as though everything was connected, as though the stars were watching over us all.`,
  `The river flowed lazily through the valley, its waters clear and shimmering in the afternoon sun. The banks were lined with wildflowers, their colors vivid against the deep green of the grass. The sound of the water was soothing, its steady current a reminder of the passage of time. As I sat on a large rock by the edge of the river, I watched the water glide past, carrying with it the stories of the mountains, the rain, and everything that had come before. Dragonflies darted above the surface, their wings flashing in the sunlight. The breeze was gentle, carrying with it the scent of fresh water and earth. It was a place of peace, where the world seemed to slow down and allow for moments of reflection. There was a beauty in the quiet simplicity of nature, in the way everything seemed to fall into place when given the space to breathe.`,
];

let generateBtn = document.getElementById("button");
let input = document.getElementById("input");
let output = document.getElementById("output");

generateBtn.addEventListener("click", function () {
  let random = Math.floor(Math.random() * text.length);
  let value = input.value;

  if (value === "" || isNaN(value) || value < 0 || value > 9) {
    output.innerHTML = "";
    return (output.innerHTML = `<p>${text[random]}</p>`);
  } else {
    let tempText = text.slice(0, value);
    return (output.innerHTML = tempText
      .map((item) => `<p>${item}</p>`)
      .join(""));
  }
});
